[flask]
secret_key = SDC
debug = false

[storage]
; Windows dev example:   C:\Users\you\my_app\uploads
; Ubuntu deploy example: /var/www/my_app/uploads
pdfs_folder = data\pdfs
thumbnails_folder = data\thumbnails
max_content_length_mb = 50